networks:
  default: "localnet"
  localnet:
    url: "http://localhost:4000/api"
  studionet:
    url: "https://studio.genlayer.com/api"
  testnet_bradbury:
    url: "https://rpc-bradbury.genlayer.com"
